common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 1;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /*public static function find()
    {
        return parent::find()->where('user.status = 0');
    }*/
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }
    public static function findUserByID($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }
    /**
    * Finds user by email
    *
    * @param string $email
    * @return static|null
    */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoles()
    {
        return $this->hasOne(Role::className(), ['id' => 'role']);
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\ForgotPasswordForm;
use common\models\User;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\web\Controller;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error','forgot-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','lock'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            /*'error' => [
                'class' => 'yii\web\ErrorAction',
            ],*/
        ];
    }

    public function actionError(){

        $this->layout ="error/main";
        $exception = Yii::$app->errorHandler->exception;
        return $this->render('error',['error'=>$exception]);

    }
    public function actionLogin() {
        $this->layout = "login/main";

        if (!Yii::$app->user->isGuest) {
            return $this->redirect(\Yii::$app->urlManager->createUrl("dashboard/index"));

        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(\Yii::$app->urlManager->createUrl("dashboard/index"));
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
    public function actionForgotPassword(){

        $this->layout = "login/main";
        $model = new ForgotPasswordForm();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if($model->load(Yii::$app->request->post())){
            $errors = ActiveForm::validate($model);
            if($errors){
                return $errors;
            }else {
                Yii::$app->getSession()->setFlash('success', [
                    'type' => 'success',
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-ok-sign',
                    'message' => 'Reset Password link has been sent to your email address',
                    'title' => 'Email Sent',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
                return $this->redirect(\Yii::$app->urlManager->createUrl("site/login"));
            }
        }
        return $this->render('forgot-password',[
            'model' => $model
        ]);
    }
    public function actionLock()
    {
        $this->layout = "login/main";

        $user = User::findIdentity(\Yii::$app->user->identity->id);
        $user->screenlock = ACTIVE;
        $user->save(false);

        $model = new LoginForm();
        $model->username = \Yii::$app->user->identity->username;
        if($model->load(Yii::$app->request->post()) && $model->unlock()){
            return $this->redirect(\Yii::$app->urlManager->createUrl("dashboard/index"));
        }
        return $this->render('lock',[
        'model' => $model,
            ]);

    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(\Yii::$app->urlManager->createUrl("site/login"));
    }
}

backend/controllers/UserController.php
<?php
namespace backend\controllers;
use backend\components\CustController;
use common\models\ChangePasswordForm;
use Yii;
use yii\web\Controller;
use yii\web\Response;
use yii\widgets\ActiveForm;
use kartik\growl\Growl;
use yii\helpers\Html;
/**
 * Site controller
 */
class UserController extends CustController
{


    public function actionProfile()
    {
        return $this->render('profile');
    }
    public function actionEditProfile(){
        return $this->render('editprofile');
    }


    public function actionChangePassword(){
        $model = new ChangePasswordForm();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
             return ActiveForm::validate($model);
        }
        if(Yii::$app->request->post() && $model->load(Yii::$app->request->post())){
                $errors = ActiveForm::validate($model);
            if($errors){
                return $errors;
            }else{
                if($model->resetPassword()){
                    Yii::$app->getSession()->setFlash('success', [
                        'type' => 'success',
                        'duration' => 12000,
                        'icon' => 'glyphicon glyphicon-ok-sign',
                        'message' => 'You have changed your password successfully',
                        'title' => 'Password Changed',
                        'positonY' => 'top',
                        'positonX' => 'right'
                    ]);
                  return $this->redirect(\Yii::$app->urlManager->createUrl("user/change-password"));
                }

            }
        }



        return $this->render('changepassword',['model'=>$model]);
    }

}

backend/views/layouts/first_nav.php
<div id="topbar-first" class="topbar">
    <div class="container">
        <div class="topbar-brand hidden-xs">
            <a class="navbar-brand" href="<?= Yii::$app->homeUrl; ?>" id="text-logo"><?= APP_NAME; ?> </a>
        </div>
        <div class="topbar-actions pull-right">
            <ul class="nav">
                <li class="dropdown account">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <div class="user-title pull-left hidden-xs">
                            <strong><?php echo Yii::$app->user->identity->first_name; ?></strong><br/><span
                                class="truncate"><?php echo Yii::$app->user->identity->roles->role_name; ?></span>
                        </div>

                        <img id="user-account-image" class="img-rounded"
                             src="<?= Yii::$app->homeUrl; ?>/default_image/default_user.jpg"
                             height="32" width="32" alt="32x32" data-src="holder.js/32x32"
                             style="width: 32px; height: 32px;"/>

                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="<?= Yii::$app->urlManager->createAbsoluteUrl('user/profile') ?>">
                                <i class="fa fa-user"></i> My profile </a>
                        </li>
                        <li>
                            <a href="<?= Yii::$app->urlManager->createAbsoluteUrl('setting') ?>">
                                <i class="fa fa-edit"></i> Account settings </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="<?= Yii::$app->urlManager->createAbsoluteUrl('site/logout') ?>"
                               data-confirm="Want to logout?" data-method="post">
                                <i class="fa fa-sign-out"></i> Logout

                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="notifications pull-right">

            <div class="btn-group">
                <a href="#" id="icon-notifications" data-toggle="dropdown">
                    <i class="fa fa-bell animated swing"></i>
                </a>
                <span id="badge-notifications" style="display:none;"
                      class="label label-danger label-notifications">1</span>

                <!-- container for ajax response -->
                <ul id="dropdown-notifications" class="dropdown-menu">
                    <li class="dropdown-header">
                        <div class="arrow"></div>
                        Notifications
                        <div class="dropdown-header-link"><a id="mark-seen-link"
                                                             href="javascript:markNotificationsAsSeen();">Mark all as
                                seen</a>
                        </div>
                    </li>
                    <ul class="media-list">
                        <li class="new">
                            <a href="http://theta123.humhub.com/notification/entry?id=2">
                                <div class="media">

                                    <!-- show user image -->
                                    <img class="media-object img-rounded pull-left" data-src="holder.js/32x32"
                                         alt="32x32" style="width: 32px; height: 32px;"
                                         src="http://localhost/humhub/img/default_user.jpg">

                                    <!-- show space image -->

                                    <!-- show content -->
                                    <div class="media-body">

                                        <strong>Sara Schuster</strong> and <strong>David Roberts</strong> commented post
                                        "We're looking for great slogans of famous brands. Maybe...".
                                        <br> <span class="time" title="Jan 18, 2017 - 7:48 AM">2 minutes ago</span>
                                        <span class="label label-danger">New</span></div>

                                </div>
                            </a>
                        </li>
                    </ul>
                    <li>
                        <div class="dropdown-footer">
                            <a class="btn btn-default col-md-12" href="/humhub/index.php?r=notification%2Foverview">
                                Show all notifications </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </div>

</div>

backend/views/layouts/main.php
<?php
/**
 * Created by PhpStorm.
 * User: rohan
 * Date: 20/5/16
 * Time: 11:38 AM
 */

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use backend\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <?php $this->title = ucwords(Yii::$app->controller->id) . ":" . APP_NAME; ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>


<!-- start: first top navigation bar -->
<?php echo $this->render('first_nav'); ?>
<!-- end: first top navigation bar -->

<!-- start: second top navigation bar -->
<?php echo $this->render('second_nav'); ?>
<!-- end: second top navigation bar -->

<!-- start: show content (and check, if exists a sublayout -->

<div class="container">
    <?php echo $content; ?>
</div>
<!-- end: show content -->
<?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/menu.php
<?php
/**
 * Created by PhpStorm.
 * User: rohan
 * Date: 24/5/16
 * Time: 9:00 PM
 */?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><span><?=APP_NAME?></span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile">
            <div class="profile_pic">
                <img src="<?=DEFAULT_IMAGE;?>" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2><?= \Yii::$app->user->identity->first_name." ".\Yii::$app->user->identity->last_name;?></h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menus</h3>
                <ul class="nav side-menu">
                      <?php $menus = \backend\models\Menus::find()->orderBy('order')->all( );
                      foreach($menus as $menu){
                          $url = $menu->controller->controller_name."/".$menu->action->action_name
                      ?>
                    <li>
                        <a href="<?=\yii\helpers\Url::toRoute($url)?>"><i class="fa <?=$menu->icon?>"></i> <?=$menu->controller->slug?> </a>
                    </li>
                    <?php }?>
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings" href="<?php echo \Yii::$app->urlManager->createUrl("setting")?>">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" onclick="maxWindow();" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock" href="<?php echo \yii\helpers\Url::toRoute('site/lock')?>">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <?php echo \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-off" aria-hidden="true"></span>',
                \yii\helpers\Url::to(['site/logout']),
                [
                    'data-confirm' => "Want to logout?", // <-- confirmation works...
                    'data-method' => 'post',
                    'data-toggle'=>'tooltip',
                    'data-placement'=>'top',
                    'title'=>'Logout'

                ]
            );?>
            <!--<a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>-->
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

backend/views/layouts/message_panel.php
<?php
/**
 * Created by PhpStorm.
 * User: rohan
 * Date: 20/6/16
 * Time: 1:46 AM
 */
use Yii;
use yii\helpers\Html;
use kartik\growl\Growl;
?>
<?php
 foreach (Yii::$app->session->getAllFlashes() as $message):; ?>
    <?php
    echo Growl::widget([
        'type' => (!empty($message['type'])) ? $message['type'] : 'danger',
        'title' => (!empty($message['title'])) ? Html::encode($message['title']) : 'Title Not Set!',
        'icon' => (!empty($message['icon'])) ? $message['icon'] : 'fa fa-info',
        'body' => (!empty($message['message'])) ? Html::encode($message['message']) : 'Message Not Set!',
        'showSeparator' => true,
        'delay' => 1, //This delay is how long before the message shows
        'pluginOptions' => [
            'delay' => (!empty($message['duration'])) ? $message['duration'] : 3000, //This delay is how long the message shows for
            'placement' => [
                'from' => (!empty($message['positonY'])) ? $message['positonY'] : 'top',
                'align' => (!empty($message['positonX'])) ? $message['positonX'] : 'right',
            ]
        ]
    ]);
    ?>
<?php endforeach; ?>

backend/views/layouts/old_main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/second_nav.php
<div id="topbar-second" class="topbar">
    <div class="container">
        <ul class="nav ">
            <li class="visible-md visible-lg <?=\backend\components\Helper::isMenuActive('dashboard','index');?> dashboard">
                <a class="<?=\backend\components\Helper::isMenuActive('dashboard','index');?> dashboard" href="<?php echo Yii::$app->urlManager->createAbsoluteUrl('dashboard') ?>"><i
                        class="fa fa-tachometer"></i><br/>Dashboard</a></li>
            <li class="visible-md visible-lg <?=\backend\components\Helper::isMenuActive('salons','index');?> directory">
                <a class="<?=\backend\components\Helper::isMenuActive('salons','index');?> directory" href="<?php echo Yii::$app->urlManager->createAbsoluteUrl('salons') ?>"><i
                        class="fa fa-scissors"></i><br/>Salons & Spa</a>
            </li>
            <li class="visible-md visible-lg  directory">
                <a class=" directory" href="<?php echo Yii::$app->urlManager->createAbsoluteUrl('users') ?>"><i
                        class="fa fa-users"></i><br/>Users</a>
            </li>

            <li class="dropdown visible-xs visible-sm">
                <a href="#" id="top-dropdown-menu" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-align-justify"></i><br>
                    Menu <b class="caret"></b></a>
                <ul class="dropdown-menu">

                    <li class="active">
                        <a class=" active dashboard" href="javascript:void(0);">Dashboard</a></li>
                    <li class="">
                        <a class=" directory" href="javascript:void(0);">Directory</a></li>

                </ul>
            </li>
        </ul>

    </div>
</div>

backend/views/layouts/top-navigation.php
<?php
/**
 * Created by PhpStorm.
 * User: rohan
 * Date: 24/5/16
 * Time: 9:06 PM
 */
?>
<div class="top_nav">

    <div class="nav_menu">
        <nav class="" role="navigation">
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="<?=DEFAULT_IMAGE;?>" alt=""><?= \Yii::$app->user->identity->first_name." ".\Yii::$app->user->identity->last_name;?>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="<?=\yii\helpers\Url::toRoute("user/profile")?>">  Profile</a>
                        </li>
                        <li>
                            <a href="<?php echo \Yii::$app->urlManager->createUrl("setting")?>">
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><?php echo \yii\helpers\Html::a(
                                'Logout',
                                \yii\helpers\Url::to(['site/logout']),
                                [
                                    'data-confirm' => "Want to logout?", // <-- confirmation works...
                                    'data-method' => 'post',
                                ]
                            );?>
                        </li>
                    </ul>
                </li>

                <li role="presentation" data-toggle="tooltip" title="Request" class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle info-number" data-toggle="tooltip" data-placement="left" title="Notification">
                        <i class="fa fa-ticket" style="font-size: 26px;"></i>
                       <?php if(!true){?> <span class="badge bg-green">6</span><?php } ?>
                    </a>
                </li>

            </ul>
        </nav>
    </div>

</div>